"""
schemas.py
==========
Agentic AML Compliance Workflow — Core Data Contracts
US Equities · OFAC SDN / BSA / FinCEN

These are the canonical data contracts for the four-agent pipeline.
Every agent, every data source adapter, every test fixture must
conform to these schemas. Do not pass raw dicts between components.

Dependencies:
    pip install pydantic>=2.0
"""

from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Literal
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, field_validator, model_validator


# ─────────────────────────────────────────────────────────────
# AML FLAG
# ─────────────────────────────────────────────────────────────

# Supported flag types for US equities under BSA/OFAC.
# Extend this literal for additional typologies as needed.
AMLFlagType = Literal[
    "SANCTIONS_NAME_MATCH",   # Counterparty name matches or partially matches OFAC SDN
    "SANCTIONS_LEI_MATCH",    # Counterparty LEI directly matches a sanctioned entity
    "UNUSUAL_VOLUME",         # Trade size anomalous vs. counterparty's 24-month history
    "STRUCTURING",            # Pattern of trades designed to stay below reporting thresholds
    "LAYERING",               # Rapid buy/sell pattern consistent with wash trading
    "JURISDICTION_RISK",      # Counterparty domiciled in FATF high-risk or monitored jurisdiction
]

# Sanctions lists recognized by this system (US-centric).
SanctionsList = Literal[
    "OFAC_SDN",           # OFAC Specially Designated Nationals list
    "OFAC_CONSOLIDATED",  # OFAC Consolidated Sanctions list
    "FINCEN_314A",        # FinCEN Section 314(a) list
    "NONE",               # Flag generated by internal rule, not a named external list
]


class AMLFlag(BaseModel):
    """
    Represents a single AML alert attached to a trade.
    Generated upstream by the firm's screening system before
    the trade enters this pipeline.

    confidence_score ranges:
      < 0.30  → auto-clearance zone (pipeline does not process these)
      0.30–0.85 → investigation zone  (this pipeline handles these)
      > 0.85  → auto-escalation zone (route directly to human, skip autonomous pipeline)

    These thresholds are defaults. Your compliance policy defines
    the actual values — document your decision in the architecture reference.
    """

    flag_id: UUID = Field(default_factory=uuid4)
    flag_type: AMLFlagType
    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score from the upstream screening system. 0.0–1.0.",
    )
    matched_entity: str = Field(
        description="The entity name or identifier that triggered the flag."
    )
    matched_list: SanctionsList
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    generating_system: str = Field(
        description="Identifier of the upstream system that raised this flag. "
                    "Used for audit trail and false-positive feedback loops.",
        examples=["OFAC-SCREENER-V2", "INTERNAL-AML-ENGINE"],
    )

    @field_validator("confidence_score")
    @classmethod
    def score_must_be_in_investigation_zone(cls, v: float) -> float:
        """
        Trades that reach this pipeline should already have been filtered
        by the upstream screening system to the investigation zone (0.30–0.85).
        Scores outside this range indicate a routing error upstream.

        # [DEV] ADJUST THESE THRESHOLDS TO YOUR COMPLIANCE POLICY ────────────
        # 0.30 and 0.85 are reference defaults, not regulatory requirements.
        # Your compliance team and legal counsel define the actual values.
        # Change the constants in the two if-statements below.
        # Also update the matching thresholds in aml_taxonomy.json under
        # "confidence_thresholds" so the triage agent receives the correct values.
        # ──────────────────────────────────────────────────────────────────────
        """
        if v < 0.30:
            raise ValueError(
                f"confidence_score {v:.2f} is below the investigation threshold (0.30). "
                "This trade should have been auto-cleared upstream. Check routing logic."
            )
        if v > 0.85:
            raise ValueError(
                f"confidence_score {v:.2f} exceeds the auto-escalation threshold (0.85). "
                "This trade should have been routed directly to human review. "
                "Check routing logic."
            )
        return v


# ─────────────────────────────────────────────────────────────
# TRADE
# ─────────────────────────────────────────────────────────────

class Trade(BaseModel):
    """
    Canonical trade record for an institutional equity trade.
    Scope: US equities, BSA/AML compliance pipeline.

    This is NOT a full FIX message or a settlement record.
    It contains the fields required by the four-agent AML pipeline.
    Your trade capture system will need an adapter to map from its
    internal representation to this schema.

    LEI format: 20-character alphanumeric string (ISO 17442).
    ISIN format: 12-character alphanumeric string (ISO 6166).
    CUSIP format: 9-character alphanumeric string (US/CA equities).
    """

    # ── Identity ──────────────────────────────────────────────
    trade_id: UUID = Field(
        default_factory=uuid4,
        description="Globally unique trade identifier. Carries through to the audit log and approval token.",
    )

    # ── Security ──────────────────────────────────────────────
    security_isin: str = Field(
        description="International Securities Identification Number. 12-character alphanumeric.",
        examples=["US0378331005"],  # Apple Inc.
    )
    security_cusip: str | None = Field(
        default=None,
        description="CUSIP identifier. 9-character. Populated for US/CA equities. "
                    "Optional — ISIN is the primary identifier.",
        examples=["037833100"],
    )
    security_description: str = Field(
        description="Human-readable security name. Used in exception report, not for data queries.",
        examples=["Apple Inc. Common Stock"],
    )

    # ── Counterparty ──────────────────────────────────────────
    counterparty_name: str = Field(
        description="Legal name of the counterparty. This is the field that may trigger "
                    "a SANCTIONS_NAME_MATCH flag. NOT used for LEI queries — use counterparty_lei.",
    )
    counterparty_lei: str = Field(
        description="Legal Entity Identifier. 20-character alphanumeric (ISO 17442). "
                    "This is the authoritative identifier for all database queries. "
                    "The investigation agent must query by LEI, never by name.",
        examples=["7H6GLXDRUGQFU57RNE97"],
    )
    counterparty_country: str = Field(
        description="Counterparty domicile country. ISO 3166-1 alpha-2. "
                    "Used for JURISDICTION_RISK flag assessment.",
        examples=["US", "GB", "DE"],
    )

    # ── Trade Economics ───────────────────────────────────────
    trade_side: Literal["BUY", "SELL"]
    quantity: int = Field(
        gt=0,
        description="Number of shares. Must be a positive integer.",
    )
    execution_price: Decimal = Field(
        gt=Decimal("0"),
        description="Price per share at execution. USD. "
                    "Stored as Decimal to preserve financial precision.",
    )
    trade_value: Decimal = Field(
        gt=Decimal("0"),
        description="Total trade value in USD. Should equal quantity × execution_price. "
                    "Validated by model_validator below.",
    )
    currency: str = Field(
        default="USD",
        description="ISO 4217 currency code. Default USD for US equities scope.",
        examples=["USD"],
    )

    # ── Settlement ────────────────────────────────────────────
    settlement_date: date = Field(
        description="Expected settlement date. US equities: T+2 standard. "
                    "Mismatches between execution_timestamp and settlement_date "
                    "can be an AML signal — do not normalize this field.",
    )
    execution_timestamp: datetime = Field(
        description="UTC timestamp of trade execution. Always store in UTC.",
    )

    # ── Internal Identifiers ──────────────────────────────────
    trader_id: str = Field(
        description="Internal identifier of the trader who executed the trade. "
                    "Written to audit log. Not exposed to external data sources.",
    )
    desk_id: str = Field(
        description="Trading desk identifier. Used for escalation routing — "
                    "senior compliance officer assignment may depend on desk.",
        examples=["INST-EQ-NY", "INST-EQ-LDN"],
    )

    # ── AML Flag ──────────────────────────────────────────────
    aml_flag: AMLFlag | None = Field(
        default=None,
        description="AML flag attached by the upstream screening system. "
                    "None if the trade was not flagged. "
                    "The pipeline should only be invoked when this field is populated.",
    )

    # ── Validators ────────────────────────────────────────────

    @field_validator("security_isin")
    @classmethod
    def validate_isin(cls, v: str) -> str:
        if len(v) != 12 or not v.isalnum():
            raise ValueError(
                f"Invalid ISIN '{v}'. Must be exactly 12 alphanumeric characters (ISO 6166)."
            )
        return v.upper()

    @field_validator("counterparty_lei")
    @classmethod
    def validate_lei(cls, v: str) -> str:
        if len(v) != 20 or not v.isalnum():
            raise ValueError(
                f"Invalid LEI '{v}'. Must be exactly 20 alphanumeric characters (ISO 17442)."
            )
        return v.upper()

    @field_validator("counterparty_country")
    @classmethod
    def validate_country_code(cls, v: str) -> str:
        if len(v) != 2 or not v.isalpha():
            raise ValueError(
                f"Invalid country code '{v}'. Must be ISO 3166-1 alpha-2 (e.g. 'US', 'GB')."
            )
        return v.upper()

    @field_validator("execution_timestamp")
    @classmethod
    def timestamp_must_be_utc(cls, v: datetime) -> datetime:
        if v.tzinfo is None:
            raise ValueError(
                "execution_timestamp must be timezone-aware (UTC). "
                "Received a naive datetime. Use datetime.now(timezone.utc) or attach tzinfo."
            )
        return v

    @model_validator(mode="after")
    def validate_trade_value(self) -> "Trade":
        """
        Verify that trade_value is consistent with quantity × execution_price.
        Allows a tolerance of ±0.01 USD to account for rounding in upstream systems.
        """
        expected = Decimal(str(self.quantity)) * self.execution_price
        delta = abs(self.trade_value - expected)
        if delta > Decimal("0.01"):
            raise ValueError(
                f"trade_value {self.trade_value} is inconsistent with "
                f"quantity ({self.quantity}) × execution_price ({self.execution_price}) "
                f"= {expected}. Delta: {delta}. Check upstream trade capture system."
            )
        return self

    def to_pipeline_string(self) -> str:
        """
        Serializes the trade into a structured plain-text string for injection
        into agent prompts. Agents receive this string, not the raw Pydantic object.

        Format is intentionally verbose and labeled so the LLM can parse
        each field without ambiguity.
        """
        flag_section = "NONE"
        if self.aml_flag:
            flag_section = (
                f"  Type: {self.aml_flag.flag_type}\n"
                f"  Confidence score: {self.aml_flag.confidence_score:.2f}\n"
                f"  Matched entity: {self.aml_flag.matched_entity}\n"
                f"  Matched list: {self.aml_flag.matched_list}\n"
                f"  Generating system: {self.aml_flag.generating_system}"
            )

        return (
            f"TRADE ID: {self.trade_id}\n"
            f"SECURITY: {self.security_description} | ISIN: {self.security_isin}"
            + (f" | CUSIP: {self.security_cusip}" if self.security_cusip else "")
            + f"\n"
            f"SIDE: {self.trade_side} | QTY: {self.quantity:,} shares "
            f"@ {self.currency} {self.execution_price} = {self.currency} {self.trade_value:,.2f}\n"
            f"COUNTERPARTY NAME: {self.counterparty_name}\n"
            f"COUNTERPARTY LEI:  {self.counterparty_lei}\n"
            f"COUNTERPARTY COUNTRY: {self.counterparty_country}\n"
            f"SETTLEMENT DATE: {self.settlement_date.isoformat()}\n"
            f"EXECUTION TIME: {self.execution_timestamp.isoformat()}\n"
            f"DESK: {self.desk_id} | TRADER: {self.trader_id}\n"
            f"AML FLAG:\n{flag_section}"
        )

    @classmethod
    def from_event(cls, event: dict) -> "Trade":
        """
        Entry point for trade events arriving from upstream systems.
        Validates schema at the pipeline boundary — before any agent sees the data.
        Raises ValidationError (Pydantic) if the event is malformed.

        This is the correct place to catch bad data. Do not let malformed
        trade data propagate into the agent pipeline.
        """
        return cls.model_validate(event)


# ─────────────────────────────────────────────────────────────
# AGENT RESULT — pipeline state carrier
# ─────────────────────────────────────────────────────────────

AgentStatus = Literal["continue", "escalate", "halt"]


class AgentResult(BaseModel):
    """
    What every agent returns to the orchestrator.
    The orchestrator reads `status` before invoking the next agent.

    continue  → proceed to next agent in sequence
    escalate  → route directly to human review, skip remaining agents
    halt      → block trade, do not route to human review, flag for investigation
    """

    agent_name: str
    output: str
    status: AgentStatus = "continue"
    reason: str | None = Field(
        default=None,
        description="Required when status is 'escalate' or 'halt'. "
                    "Written to audit log and surfaced in human review queue.",
    )

    @model_validator(mode="after")
    def reason_required_for_non_continue(self) -> "AgentResult":
        if self.status != "continue" and not self.reason:
            raise ValueError(
                f"AgentResult with status='{self.status}' must include a reason. "
                "The reason is written to the audit log and shown to the compliance officer."
            )
        return self
