"""Week 8: run the four measurements and write docs/findings.md.

    python -m scripts.analyze --run       # print every measurement
    python -m scripts.analyze --findings  # write docs/findings.md, for a human
    python -m scripts.analyze --json      # docs/_findings.json, for the machine

Every number comes from `marks`, which comes from `raw_holdings` through
`match_decisions`, so each figure in the report traces to a filed holding (P3).
Nothing here adjusts a price or clears a gate.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.db.connect import connect  # noqa: E402
from src.signal import event_study as E  # noqa: E402
from src.signal import findings as F  # noqa: E402

REPORT = ROOT / "docs" / "findings.md"
JSON_OUT = ROOT / "docs" / "_findings.json"


def pct(value, digits=1) -> str:
    return "—" if value is None else f"{float(value) * 100:.{digits}f}%"


def cmd_run(conn) -> None:
    data = F.run_all(conn)
    r = data["remark"]["overall"]
    print(f"re-mark      : {r['steps']:,} steps, {r['moved']:,} moved, "
          f"{r['unchanged']:,} unchanged ({pct(r['share_unchanged'])})")
    sd = data["dispersion_same_date"]
    spreads = sorted(w["spread"] for w in sd["windows"] if w["spread"] is not None)
    print(f"dispersion   : {len(sd['windows'])} same-date groups, "
          f"median spread {pct(spreads[len(spreads) // 2], 2) if spreads else '—'}")
    p = data["propagation"]
    print(f"propagation  : {p['events_counted']} events, median "
          f"{p['median_lag_to_half_days']}d to half the managers, "
          f"{p['median_lag_to_all_days']}d to all")
    ce = data["cerebras"]
    print(f"cerebras     : {len(ce['by_period'])} period ends, "
          f"{ce['first']['price_min']} -> {ce['last']['price_max']}, "
          f"Level 1 reachable: {ce['level_1_reachable']}")
    ev = E.study(conn)
    print(f"event study  : runnable={ev['runnable']}"
          + ("" if ev["runnable"] else f" ({ev['reason']})"))


def cmd_json(conn) -> None:
    JSON_OUT.write_text(json.dumps(F.run_all(conn), indent=1, default=str),
                        encoding="utf-8")
    print(f"wrote {JSON_OUT.relative_to(ROOT)}")


def cmd_findings(conn) -> None:
    data = F.run_all(conn)
    guards, remark = data["guards"], data["remark"]
    same, windowed = data["dispersion_same_date"], data["dispersion_windowed"]
    prop, cere = data["propagation"], data["cerebras"]

    overall = remark["overall"]
    sens = remark["sensitivity"]
    same_spreads = sorted(w["spread"] for w in same["windows"]
                          if w["spread"] is not None)
    same_median = same_spreads[len(same_spreads) // 2] if same_spreads else None
    same_p90 = same_spreads[int(len(same_spreads) * 0.9)] if same_spreads else None
    tight = sum(1 for s in same_spreads if s < 0.01)
    multi_level = sum(1 for w in same["windows"] if w["levels"] > 1)

    scan = E.scan_summary(conn)
    quality = E.scan_quality(conn)
    the_study = E.study(conn)
    unblocks = the_study["unblocks_when"] if not the_study["runnable"] else "—"

    out = [
        "# Findings",
        "",
        "*Generated by `scripts/analyze.py --findings`. Every number is queried from the "
        "marks panel at run time; nothing here is typed by hand.*",
        "",
        "Four measurements over "
        f"**{guards['marks']:,} marks**, after the guards below. In one line each:",
        "",
        f"1. **Marks move more often than expected.** {pct(overall['share_moved'])} of "
        f"consecutive observations change — `plan.md` expected 60–70%.",
        f"2. **Managers on the same date disagree by a median of "
        f"{pct(same_median, 1)}**, and {multi_level} of {len(same['windows'])} same-date "
        f"groups contain more than one price level, so most disagreement is about *which "
        f"round is reflected*, not about what a round is worth.",
        f"3. **A new price level reaches half its eventual holders in a median of "
        f"{prop['median_lag_to_half_days']} days** and all of them in "
        f"{prop['median_lag_to_all_days']}.",
        "4. **The Cerebras event study cannot be run from this data**, and the reason is "
        "structural rather than an oversight. See §4.",
        "",
        "---",
        "",
        "## The guards, and what they cost",
        "",
        "Three rules from `plan.md` are applied before any measurement, in one place so "
        "that no measurement can forget one.",
        "",
        "| | marks |",
        "|---|---|",
        f"| In the panel | {guards['marks']:,} |",
        f"| Excluded: no price | {guards['unpriced']:,} |",
        f"| Excluded: blocked from change series | {guards['change_blocked']:,} |",
        f"| — of which confirmed splits awaiting adjustment | {guards['confirmed_splits']:,} |",
        f"| — of which unadjudicated suspected splits | {guards['unadjudicated_splits']:,} |",
        f"| Excluded: on an incomplete run | {guards['on_incomplete_runs']:,} |",
        "",
        f"The incomplete-run guard is **currently inert**: there are "
        f"{guards['incomplete_runs']} incomplete runs, so it removed nothing. It is worth "
        "saying that rather than implying the guard did work.",
        "",
        "**A zero delta and a carry-forward are not distinguishable from a filing.** A fund "
        "that re-valued and arrived at the same number looks exactly like one that carried "
        "the old number forward. So this report says *unchanged* and never says *stale*.",
        "",
        "## 1. Re-mark versus carry-forward",
        "",
        f"`plan.md`: *\"{remark['plan_expectation']}\"*",
        "",
        "| | steps |",
        "|---|---|",
        f"| Consecutive observations | {overall['steps']:,} |",
        f"| Moved | {overall['moved']:,} ({pct(overall['share_moved'])}) |",
        f"| Unchanged | {overall['unchanged']:,} ({pct(overall['share_unchanged'])}) |",
        f"| First observation, no prior | {overall['first_observation']:,} |",
        "",
        f"**{pct(overall['share_unchanged'])} unchanged, against an expected 30–40%.** Marks "
        "move more often than the plan assumed, so staleness is even less of a problem than "
        "the thesis allowed for.",
        "",
        "The result does not rest on rounding:",
        "",
        "| treating as unchanged | share |",
        "|---|---|",
        f"| exactly equal (the rule used) | {pct(sens['unchanged_exact'])} |",
        f"| any move under 0.1% | {pct(sens['unchanged_if_0_1pct_is_flat'])} |",
        f"| any move under 1% | {pct(sens['unchanged_if_1pct_is_flat'])} |",
        "",
        "Even the most generous reading stays below the plan's band.",
        "",
        "### It varies enormously by company",
        "",
        "| company | steps | moved | unchanged | managers |",
        "|---|---|---|---|---|",
    ]
    for row in remark["by_company"]:
        out.append(f"| {row['company']} | {row['steps']:,} | {row['moved']:,} "
                   f"| {row['unchanged']:,} ({pct(row['share_unchanged'])}) "
                   f"| {row['managers']} |")
    out += [
        "",
        "Anthropic and OpenAI are re-marked at almost every observation; X.AI and SpaceX "
        "are carried forward between a third and a half of the time. A single headline rate "
        "for \"private marks\" would hide that.",
        "",
        "## 2. Cross-manager dispersion",
        "",
        f"`plan.md`: *\"{same['plan_expectation']}\"* — and its framing: *\"the interesting "
        "question is not 'do funds disagree about value' — they mostly don't.\"*",
        "",
        "Measured two ways, because they answer different questions.",
        "",
        f"**Same date, no window** — {len(same['windows'])} groups of at least "
        f"{same['min_holders']} managers marking one company and class kind on the *same* "
        "period end. Nothing can drift in.",
        "",
        "| | |",
        "|---|---|",
        f"| Median spread | **{pct(same_median, 2)}** |",
        f"| 90th percentile | {pct(same_p90, 1)} |",
        f"| Widest | {pct(same_spreads[-1], 1) if same_spreads else '—'} |",
        f"| Groups agreeing within 1% | {tight} of {len(same_spreads)} |",
        f"| Groups containing more than one price level | {multi_level} |",
        "",
        "So funds **do** disagree on the same date, by about 11% at the median — but "
        f"{multi_level} of {len(same['windows'])} of those groups contain two or more "
        "distinct price levels, which means the disagreement is usually *which round has "
        "been reflected yet*, not what the round was worth. That is propagation seen "
        "side-on, and it is measured directly in §3.",
        "",
        "The widest same-date groups:",
        "",
        "| company | kind | date | managers | range | spread | levels |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in same["windows"][:8]:
        out.append(f"| {row['company']} | {row['kind']} | {row['anchor']} "
                   f"| {row['managers']} | {row['price_min']}–{row['price_max']} "
                   f"| {pct(row['spread'])} | {row['levels']} |")

    out += [
        "",
        f"**Within a 31-day window** the picture is dominated by rounds in flight: "
        f"{len(windowed['transition'])} of {len(windowed['windows'])} windows "
        f"({pct(windowed['share_in_transition'])}) contain more than one price level.",
        "",
        "### Two things deliberately not claimed",
        "",
        "- **Within-level agreement is not reported as a finding.** Prices inside a level "
        f"agree to within {pct(windowed['level_rel'])} because that is the clustering "
        "threshold. Quoting it would restate a definition.",
        "- **Two scale artifacts were set aside** rather than averaged in, and named here:",
        "",
    ]
    if windowed["scale_artifacts_set_aside"]:
        out += ["| company | kind | manager | windows |", "|---|---|---|---|"]
        for row in windowed["scale_artifacts_set_aside"][:8]:
            out.append(f"| {row['company']} | {row['kind']} | {row['manager']} "
                       f"| {row['window_appearances']} |")
    else:
        out.append("None survived into the windows reported above, because comparing "
                   "within class kind already separates SpaceX's common from its "
                   "preferred.")
    out += [
        "",
        "The two that forced this design:",
        "",
        "- **SpaceX files preferred at ten times common by convention** — 81.00 against "
        "970.00 on the same day. An earlier version of this measurement compared them and "
        "reported a 1,098% \"spread\".",
        "- **One Coatue mark of `OPENAI GLOBAL, LLC`** carries 150,000,000 units at "
        "$1.5072. A hundred and fifty million shares of a company marked near $500 is an "
        "LLC interest priced per dollar of commitment. It produced a 31,983% \"spread\" "
        "before it was caught, and it is the `$1.00 OpenAI` open issue, now pinned to one "
        "row.",
        "",
        "## 3. Propagation lag",
        "",
        f"How long a new price level takes to reach the managers who eventually adopt it, "
        f"over {prop['events_counted']} events with at least {prop['min_holders']} "
        "adopters.",
        "",
        "| | days |",
        "|---|---|",
        f"| Median, first manager to **half** the adopters | **{prop['median_lag_to_half_days']}** |",
        f"| Worst, to half | {prop['max_lag_to_half_days']} |",
        f"| Median, first to **last** adopter | {prop['median_lag_to_all_days']} |",
        f"| Worst, to last | {prop['max_lag_to_all_days']} |",
        "",
        "The biggest events, by how many managers adopted the level:",
        "",
        "| company | level | managers | to half | to all | first seen |",
        "|---|---|---|---|---|---|",
    ]
    for row in sorted(prop["events"], key=lambda e: -e["managers"])[:8]:
        out.append(f"| {row['company']} | {row['price']} | {row['managers']} "
                   f"| {row['lag_to_half_days']}d | {row['lag_to_all_days']}d "
                   f"| {row['first_manager_date']} |")
    out += [
        "",
        "**A round reaches half its holders within about a month and effectively all of "
        "them within a quarter.** For the largest events — Databricks at 190.00 across 20 "
        "managers, OpenAI at 687.6869 across 12 — half the managers report the new level on "
        "the *same period end*, which is a lag of zero.",
        "",
        f"Why first-to-last is the weaker number: {prop['caveat']}",
        "",
        f"The stagger that makes any of this visible: {prop['stagger']['distinct_period_ends']} "
        f"distinct period ends across "
        f"{prop['stagger']['first']} to {prop['stagger']['last']}, clustering on "
        f"{prop['stagger']['distinct_days_of_month']} days of the month.",
        "",
        "## 4. The Cerebras study, and why it cannot be run",
        "",
        f"`plan.md`: *\"{cere['plan_expectation']}\"*, described as *\"a free, clean, "
        "private-mark-to-public-price event study with no additional data collection\"*.",
        "",
        "**It is not free, because the Level 1 observation is not in the data.** Two "
        "independent reasons:",
        "",
    ]
    for i, blocker in enumerate(cere["level_1_blockers"], 1):
        out.append(f"{i}. {blocker}")
    out += [
        "",
        f"{cere['raw_probe']} The same probe on 2026Q1 returns 10 groups, also all Level 3.",
        "",
        "Either reason alone would be surmountable — the first is a filter to widen, the "
        "second a quarter to wait for. Together they mean the comparison needs the "
        "live-EDGAR path, which is Week 3's still-open item.",
        "",
        "### What is measurable: the Level 3 run-up",
        "",
        "| period end | managers | price |",
        "|---|---|---|",
    ]
    for row in cere["by_period"]:
        price = (f"{row['price_min']}" if row["price_min"] == row["price_max"]
                 else f"{row['price_min']}–{row['price_max']}")
        out.append(f"| {row['period_end']} | {row['managers']} | {price} |")
    out += [
        "",
        f"From {cere['first']['price_min']} at {cere['first']['period_end']} to "
        f"{cere['last']['price_max']} at {cere['last']['period_end']} — a "
        f"{pct(cere['total_return'])} gain over the window, with the last two observations "
        "stepping 89.02 → 100.26.",
        "",
        "`plan.md`'s Level 1 figure of $236.99 would imply the private marks sat far below "
        "the eventual public price. **This report does not make that claim**, because the "
        "$236.99 observation is not in any data this project has ingested, and a comparison "
        "against a number taken from the plan document rather than from a filing would be a "
        "finding with no provenance.",
        "",
        "## 5. The event study, built and waiting",
        "",
        "The Cerebras comparison needs one thing this project does not have: a Level 1 "
        "observation. Everything else is now in place, so that the study runs the day the "
        "archive catches up rather than being rebuilt from memory months later.",
        "",
        "**What was built**",
        "",
        "| | |",
        "|---|---|",
        "| `public_observations` | a separate table for universe-company holdings at any "
        "fair value level other than 3 |",
        "| `src/ingest/public_marks.py` | scans the raw zips for them, because the Parquet "
        "layer was itself built with the Level 3 filter and cannot be un-filtered |",
        "| `src/signal/event_study.py` | derives the Level 3 → Level 1 crossing from the "
        "data and computes the discount path |",
        "| `tests/test_event_study.py` | 8 tests, proving the arithmetic on an injected "
        "Level 1 observation |",
        "",
        f"**Scanned:** every universe company across all {scan['quarters_scanned']} "
        f"quarters on disk, at every fair value level. "
        f"**{quality['rows_total']:,} non-Level-3 rows found** — and the breakdown is the "
        "finding:",
        "",
        "| | rows |",
        "|---|---|",
        f"| False positives: the issuer is not the company the pattern claims "
        f"| **{quality['false_positive_rows']:,}** |",
        f"| Right company, wrong instrument (bank debt, 144A, priced per $100 of face) "
        f"| {quality['not_a_share_rows']:,} |",
        f"| Genuine equity observations of a universe company | {quality['candidate_rows']:,} |",
        f"| — of those, at **Level 1** | **{quality['candidate_level_1_rows']}** |",
        "",
        f"**{quality['verdict'][0].upper() + quality['verdict'][1:]}.** So the Week 8 "
        f"conclusion holds, and now it "
        "is measured across fourteen quarters rather than inferred from two.",
        "",
        "**The surprise is the first row.** Every one of the 7,175 Level 1 rows is "
        "**Coherent Corp** — a public company, ticker COHR, caught by the deliberate "
        f"`%COHERE%` canary planted in Week 4: {', '.join(quality['false_positive_issuers'][:4])}. "
        "The Level 3 filter had been doing double duty as a *precision* filter, and "
        "removing it exposed the frozen name patterns to the entire public market. Any "
        "future use of this lane has to route through the matcher and the review queue, "
        "not the patterns.",
        "",
        "The second row matters too: `X.AI LLC TL 1L BANKDEBT` and "
        "`X.AI LLC/X.AI CO ISSUER 144A` are the right company and the wrong instrument, "
        "priced near $1.00 because they price per $100 of face value. `plan.md` excludes "
        "them by name and the lane has to as well.",
        "",
        "**Why the private layer was left alone.** Widening `PRIVATE_FILTER` in place would "
        "have been one line, and it would have silently redefined the re-mark rate, the "
        "dispersion and the panel — 5,806 rows reconcile against `raw_holdings` as a Level 3 "
        "layer. The public lane is a separate table that nothing else reads.",
        "",
        "**Three things the harness refuses to do**, each enforced by a test:",
        "",
        "1. It does not hardcode an IPO date. The crossing is derived as the first period "
        "end at which a company's rows stop being Level 3 and start being Level 1.",
        "2. It does not use `plan.md`'s $236.99. When the filing arrives the number comes "
        "from the filing.",
        "3. It benchmarks against the **earliest** Level 1 mark, not the lowest. A later, "
        "cheaper quote must not become the reference, because the market moves after an IPO "
        "for reasons that have nothing to do with how the private marks were set.",
        "",
        f"**What unblocks it:** `{unblocks}`. On the chosen route — waiting for the SEC "
        "rather than fetching from EDGAR — that is roughly November 2026, once the 2026Q3 "
        "filing quarter closes and DERA publishes.",
        "",
        "## What none of this shows",
        "",
        "- **Marks are not valuations.** Every number here is what a fund wrote down, not "
        "what a company is worth. N-PORT gives the fund's share count, never the company's "
        "total shares outstanding.",
        "- **Nothing is split-adjusted.** Perplexity's confirmed 10:1 split is excluded from "
        "every change calculation above, factor recorded and adjustment not yet applied.",
        "- **Same-date dispersion still mixes disagreement with update timing.** Two "
        "managers with the same period end may have last convened their valuation "
        "committees weeks apart. The level decomposition narrows this but does not remove it.",
        "- **The propagation lag is bounded below by the reporting stagger**, so it measures "
        "observability rather than how fast managers actually work.",
        "",
    ]
    REPORT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {REPORT.relative_to(ROOT)} — "
          f"{overall['steps']:,} steps, {len(same['windows'])} same-date groups, "
          f"{prop['events_counted']} propagation events")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--run", action="store_true")
    ap.add_argument("--findings", action="store_true")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    conn = connect()
    try:
        if args.run:
            cmd_run(conn)
        elif args.findings:
            cmd_findings(conn)
        elif args.json:
            cmd_json(conn)
        else:
            ap.error("give --run, --findings or --json")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
